// <auto-generated />
using System;
using CHMS.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHMS.DAL.Migrations
{
    [DbContext(typeof(CoastalHomestayDBContext))]
    [Migration("20260225045314_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityHomestay", b =>
                {
                    b.Property<Guid>("AmenitiesId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenitiesid");

                    b.Property<Guid>("HomestaysId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestaysid");

                    b.HasKey("AmenitiesId", "HomestaysId")
                        .HasName("pk_amenityhomestay");

                    b.HasIndex("HomestaysId")
                        .HasDatabaseName("ix_amenityhomestay_homestaysid");

                    b.ToTable("amenityhomestay", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("newvalues");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("oldvalues");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("useragent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_auditlogs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auditlogs_userid");

                    b.ToTable("auditlogs", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isavailable");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("priceoverride");

                    b.HasKey("Id")
                        .HasName("pk_availabilities");

                    b.HasIndex("HomestayId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_availabilities_homestayid_date");

                    b.ToTable("availabilities", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("checkin");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("checkout");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contactphone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deletedby");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discountamount");

                    b.Property<int>("GuestsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("guestscount");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<decimal>("PricePerNightAtBooking")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("pricepernightatbooking");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotionid");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("specialrequests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("TotalNights")
                        .HasColumnType("integer")
                        .HasColumnName("totalnights");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("totalprice");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customerid");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_bookings_deletedby");

                    b.HasIndex("HomestayId")
                        .HasDatabaseName("ix_bookings_homestayid");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_bookings_promotionid");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changedby");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("newstatus");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("oldstatus");

                    b.HasKey("Id")
                        .HasName("pk_bookingstatushistories");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_bookingstatushistories_bookingid");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_bookingstatushistories_changedby");

                    b.ToTable("bookingstatushistories", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Cancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingid");

                    b.Property<Guid>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelledby");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<decimal>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refundamount");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("refundstatus");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refundedat");

                    b.HasKey("Id")
                        .HasName("pk_cancellations");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_cancellations_bookingid");

                    b.HasIndex("CancelledBy")
                        .HasDatabaseName("ix_cancellations_cancelledby");

                    b.ToTable("cancellations", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sender");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sessionid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_chathistories");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chathistories_userid");

                    b.ToTable("chathistories", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guestid");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("hostid");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmessageat");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_conversations_bookingid");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_conversations_guestid");

                    b.HasIndex("HomestayId")
                        .HasDatabaseName("ix_conversations_homestayid");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_conversations_hostid");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("provinceid");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_districts_provinceid");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Homestay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("area");

                    b.Property<int>("Bathrooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("bathrooms");

                    b.Property<int>("Bedrooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("bedrooms");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("text")
                        .HasColumnName("cancellationpolicy");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deletedby");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HouseRules")
                        .HasColumnType("text")
                        .HasColumnName("houserules");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("locationid");

                    b.Property<int>("MaxGuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("maxguests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ownerid");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("pricepernight");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_homestays");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_homestays_deletedby");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_homestays_locationid");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_homestays_ownerid");

                    b.ToTable("homestays", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.HomestayImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("displayorder");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isprimary");

                    b.HasKey("Id")
                        .HasName("pk_homestayimages");

                    b.HasIndex("HomestayId")
                        .HasDatabaseName("ix_homestayimages_homestayid");

                    b.ToTable("homestayimages", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("districtid");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_locations_districtid");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversationid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isread");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("readat");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("senderid");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversationid");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_senderid");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isread");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("readat");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("referenceid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referencetype");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_userid");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text")
                        .HasColumnName("gatewayresponse");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("uuid")
                        .HasColumnName("transactionid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_payments_bookingid");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentUsage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("currentusage");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("deletedby");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("discountamount");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discountpercent");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("enddate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("maxdiscountamount");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("integer")
                        .HasColumnName("maxusage");

                    b.Property<decimal?>("MinBookingAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("minbookingamount");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promotions_code");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_provinces");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deviceinfo");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("replacedbytoken");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_refreshtokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refreshtokens_userid");

                    b.ToTable("refreshtokens", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingid");

                    b.Property<int?>("CleanlinessRating")
                        .HasColumnType("integer")
                        .HasColumnName("cleanlinessrating");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int?>("CommunicationRating")
                        .HasColumnType("integer")
                        .HasColumnName("communicationrating");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customerid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deletedby");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isverified");

                    b.Property<int?>("LocationRating")
                        .HasColumnType("integer")
                        .HasColumnName("locationrating");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("ReplyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replyat");

                    b.Property<string>("ReplyFromOwner")
                        .HasColumnType("text")
                        .HasColumnName("replyfromowner");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<int?>("ValueRating")
                        .HasColumnType("integer")
                        .HasColumnName("valuerating");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_bookingid");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reviews_customerid");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_reviews_deletedby");

                    b.HasIndex("HomestayId")
                        .HasDatabaseName("ix_reviews_homestayid");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.ReviewImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imageurl");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewid");

                    b.HasKey("Id")
                        .HasName("pk_reviewimages");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_reviewimages_reviewid");

                    b.ToTable("reviewimages", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permissionid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_rolepermissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_rolepermissions_permissionid");

                    b.ToTable("rolepermissions", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.SeasonalPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("enddate");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.HasKey("Id")
                        .HasName("pk_seasonalpricings");

                    b.HasIndex("HomestayId")
                        .HasDatabaseName("ix_seasonalpricings_homestayid");

                    b.ToTable("seasonalpricings", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvedat");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staffid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_supporttickets");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_supporttickets_bookingid");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_supporttickets_staffid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_supporttickets_userid");

                    b.ToTable("supporttickets", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.TicketReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticketid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_ticketreplies");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticketreplies_ticketid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ticketreplies_userid");

                    b.ToTable("ticketreplies", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatarurl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deletedby");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_users_deletedby");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_userroles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_userroles_roleid");

                    b.ToTable("userroles", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.VerificationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("documenttype");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("documenturl");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejectreason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewedat");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewedby");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submissiondate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_verificationdocuments");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_verificationdocuments_reviewedby");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_verificationdocuments_userid");

                    b.ToTable("verificationdocuments", (string)null);
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "HomestayId")
                        .HasName("pk_wishlists");

                    b.HasIndex("HomestayId")
                        .HasDatabaseName("ix_wishlists_homestayid");

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("CHMS.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("iconurl");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_amenities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_amenities_name");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("CHMS.Domain.Entities.HomestayAmenity", b =>
                {
                    b.Property<Guid>("HomestayId")
                        .HasColumnType("uuid")
                        .HasColumnName("homestayid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenityid");

                    b.HasKey("HomestayId", "AmenityId")
                        .HasName("pk_homestayamenities");

                    b.HasIndex("AmenityId")
                        .HasDatabaseName("ix_homestayamenities_amenityid");

                    b.ToTable("homestayamenities", (string)null);
                });

            modelBuilder.Entity("AmenityHomestay", b =>
                {
                    b.HasOne("CHMS.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_amenityhomestay_amenities_amenitiesid");

                    b.HasOne("CHMS.DAL.Entities.Homestay", null)
                        .WithMany()
                        .HasForeignKey("HomestaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_amenityhomestay_homestays_homestaysid");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditlogs_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Availability", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("Availabilities")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availabilities_homestays_homestayid");

                    b.Navigation("Homestay");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Booking", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "Customer")
                        .WithMany("BookingCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_customerid");

                    b.HasOne("CHMS.DAL.Entities.User", "DeletedByNavigation")
                        .WithMany("BookingDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_users_deletedby");

                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("Bookings")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_homestays_homestayid");

                    b.HasOne("CHMS.DAL.Entities.Promotion", "Promotion")
                        .WithMany("Bookings")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_promotions_promotionid");

                    b.Navigation("Customer");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Homestay");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingStatusHistories")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookingstatushistories_bookings_bookingid");

                    b.HasOne("CHMS.DAL.Entities.User", "ChangedByNavigation")
                        .WithMany("BookingStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookingstatushistories_users_changedby");

                    b.Navigation("Booking");

                    b.Navigation("ChangedByNavigation");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Cancellation", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Booking", "Booking")
                        .WithMany("Cancellations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cancellations_bookings_bookingid");

                    b.HasOne("CHMS.DAL.Entities.User", "CancelledByNavigation")
                        .WithMany("Cancellations")
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cancellations_users_cancelledby");

                    b.Navigation("Booking");

                    b.Navigation("CancelledByNavigation");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.ChatHistory", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chathistories_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Conversation", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Booking", "Booking")
                        .WithMany("Conversations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conversations_bookings_bookingid");

                    b.HasOne("CHMS.DAL.Entities.User", "Guest")
                        .WithMany("ConversationGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_guestid");

                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("Conversations")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_homestays_homestayid");

                    b.HasOne("CHMS.DAL.Entities.User", "Host")
                        .WithMany("ConversationHosts")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_hostid");

                    b.Navigation("Booking");

                    b.Navigation("Guest");

                    b.Navigation("Homestay");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.District", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_districts_provinces_provinceid");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Homestay", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "DeletedByNavigation")
                        .WithMany("HomestayDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_homestays_users_deletedby");

                    b.HasOne("CHMS.DAL.Entities.Location", "Location")
                        .WithMany("Homestays")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_homestays_locations_locationid");

                    b.HasOne("CHMS.DAL.Entities.User", "Owner")
                        .WithMany("HomestayOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_homestays_users_ownerid");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.HomestayImage", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("HomestayImages")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homestayimages_homestays_homestayid");

                    b.Navigation("Homestay");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Location", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.District", "District")
                        .WithMany("Locations")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_districts_districtid");

                    b.Navigation("District");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Message", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversationid");

                    b.HasOne("CHMS.DAL.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_senderid");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Notification", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Payment", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtokens_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Review", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("CHMS.DAL.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_bookingid");

                    b.HasOne("CHMS.DAL.Entities.User", "Customer")
                        .WithMany("ReviewCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_customerid");

                    b.HasOne("CHMS.DAL.Entities.User", "DeletedByNavigation")
                        .WithMany("ReviewDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reviews_users_deletedby");

                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("Reviews")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_homestays_homestayid");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Homestay");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.ReviewImage", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewimages_reviews_reviewid");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rolepermissions_permissions_permissionid");

                    b.HasOne("CHMS.DAL.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rolepermissions_roles_roleid");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.SeasonalPricing", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("SeasonalPricings")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasonalpricings_homestays_homestayid");

                    b.Navigation("Homestay");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.SupportTicket", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Booking", "Booking")
                        .WithMany("SupportTickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_supporttickets_bookings_bookingid");

                    b.HasOne("CHMS.DAL.Entities.User", "Staff")
                        .WithMany("SupportTicketStaffs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_supporttickets_users_staffid");

                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("SupportTicketUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supporttickets_users_userid");

                    b.Navigation("Booking");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.TicketReply", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.SupportTicket", "Ticket")
                        .WithMany("TicketReplies")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticketreplies_supporttickets_ticketid");

                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("TicketReplies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticketreplies_users_userid");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.User", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "DeletedByNavigation")
                        .WithMany("InverseDeletedByNavigation")
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_deletedby");

                    b.Navigation("DeletedByNavigation");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.UserRole", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userroles_roles_roleid");

                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userroles_users_userid");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.VerificationDocument", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.User", "ReviewedByNavigation")
                        .WithMany("VerificationDocumentReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_verificationdocuments_users_reviewedby");

                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("VerificationDocumentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verificationdocuments_users_userid");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Wishlist", b =>
                {
                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("Wishlists")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlists_homestays_homestayid");

                    b.HasOne("CHMS.DAL.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlists_users_userid");

                    b.Navigation("Homestay");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CHMS.Domain.Entities.HomestayAmenity", b =>
                {
                    b.HasOne("CHMS.Domain.Entities.Amenity", "Amenity")
                        .WithMany("HomestayAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homestayamenities_amenities_amenityid");

                    b.HasOne("CHMS.DAL.Entities.Homestay", "Homestay")
                        .WithMany("HomestayAmenities")
                        .HasForeignKey("HomestayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homestayamenities_homestays_homestayid");

                    b.Navigation("Amenity");

                    b.Navigation("Homestay");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Booking", b =>
                {
                    b.Navigation("BookingStatusHistories");

                    b.Navigation("Cancellations");

                    b.Navigation("Conversations");

                    b.Navigation("Payments");

                    b.Navigation("Review");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.District", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Homestay", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Bookings");

                    b.Navigation("Conversations");

                    b.Navigation("HomestayAmenities");

                    b.Navigation("HomestayImages");

                    b.Navigation("Reviews");

                    b.Navigation("SeasonalPricings");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Location", b =>
                {
                    b.Navigation("Homestays");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Promotion", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.SupportTicket", b =>
                {
                    b.Navigation("TicketReplies");
                });

            modelBuilder.Entity("CHMS.DAL.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BookingCustomers");

                    b.Navigation("BookingDeletedByNavigations");

                    b.Navigation("BookingStatusHistories");

                    b.Navigation("Cancellations");

                    b.Navigation("ChatHistories");

                    b.Navigation("ConversationGuests");

                    b.Navigation("ConversationHosts");

                    b.Navigation("HomestayDeletedByNavigations");

                    b.Navigation("HomestayOwners");

                    b.Navigation("InverseDeletedByNavigation");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewCustomers");

                    b.Navigation("ReviewDeletedByNavigations");

                    b.Navigation("SupportTicketStaffs");

                    b.Navigation("SupportTicketUsers");

                    b.Navigation("TicketReplies");

                    b.Navigation("UserRoles");

                    b.Navigation("VerificationDocumentReviewedByNavigations");

                    b.Navigation("VerificationDocumentUsers");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("CHMS.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("HomestayAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
