// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CHMS.DAL.Entities;
using System;
using System.Collections.Generic;

namespace CHMS.Domain.Entities;

public partial class Amenity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string IconUrl { get; set; }

    public string Category { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<Homestay> Homestays { get; set; } = new List<Homestay>();
    public virtual ICollection<HomestayAmenity> HomestayAmenities { get; set; } = new List<HomestayAmenity>();
}