// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Availability
{
    public Guid Id { get; set; }

    public Guid HomestayId { get; set; }

    public DateOnly Date { get; set; }

    public bool IsAvailable { get; set; }

    public decimal? PriceOverride { get; set; }

    public string Note { get; set; }

    public virtual Homestay Homestay { get; set; }
}