// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class BookingStatusHistory
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public string Note { get; set; }

    public Guid? ChangedBy { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual User ChangedByNavigation { get; set; }
}