// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Cancellation
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public Guid CancelledBy { get; set; }

    public string Reason { get; set; }

    public decimal RefundAmount { get; set; }

    public string RefundStatus { get; set; }

    public DateTime? RefundedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual User CancelledByNavigation { get; set; }
}