// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class ChatHistory
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string SessionId { get; set; }

    public string Message { get; set; }

    public string Sender { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}