// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Conversation
{
    public Guid Id { get; set; }

    public Guid HomestayId { get; set; }

    public Guid GuestId { get; set; }

    public Guid HostId { get; set; }

    public Guid? BookingId { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual User Guest { get; set; }

    public virtual Homestay Homestay { get; set; }

    public virtual User Host { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}