// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class District
{
    public Guid Id { get; set; }

    public Guid ProvinceId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual Province Province { get; set; }
}