// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class HomestayImage
{
    public Guid Id { get; set; }

    public Guid HomestayId { get; set; }

    public string ImageUrl { get; set; }

    public string Caption { get; set; }

    public bool IsPrimary { get; set; }

    public int DisplayOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Homestay Homestay { get; set; }
}