// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CHMS.Domain.Entities;
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Homestay
{
    public Guid Id { get; set; }

    public Guid OwnerId { get; set; }

    public Guid LocationId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal PricePerNight { get; set; }

    public int MaxGuests { get; set; }

    public int Bedrooms { get; set; }

    public int Bathrooms { get; set; }

    public decimal? Area { get; set; }

    public string CancellationPolicy { get; set; }

    public string HouseRules { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public Guid? DeletedBy { get; set; }

    public virtual ICollection<Availability> Availabilities { get; set; } = new List<Availability>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual User DeletedByNavigation { get; set; }

    public virtual ICollection<HomestayImage> HomestayImages { get; set; } = new List<HomestayImage>();

    public virtual Location Location { get; set; }

    public virtual User Owner { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<SeasonalPricing> SeasonalPricings { get; set; } = new List<SeasonalPricing>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();

    public virtual ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();
    public virtual ICollection<HomestayAmenity> HomestayAmenities { get; set; } = new List<HomestayAmenity>();
}