// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Location
{
    public Guid Id { get; set; }

    public Guid DistrictId { get; set; }

    public string Address { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual District District { get; set; }

    public virtual ICollection<Homestay> Homestays { get; set; } = new List<Homestay>();
}