// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Province
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<District> Districts { get; set; } = new List<District>();
}