// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Review
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid HomestayId { get; set; }

    public int Rating { get; set; }

    public int? CleanlinessRating { get; set; }

    public int? LocationRating { get; set; }

    public int? ValueRating { get; set; }

    public int? CommunicationRating { get; set; }

    public string Comment { get; set; }

    public string ReplyFromOwner { get; set; }

    public DateTime? ReplyAt { get; set; }

    public bool IsVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public Guid? DeletedBy { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual User Customer { get; set; }

    public virtual User DeletedByNavigation { get; set; }

    public virtual Homestay Homestay { get; set; }

    public virtual ICollection<ReviewImage> ReviewImages { get; set; } = new List<ReviewImage>();
}