// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class User
{
    public Guid Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PasswordHash { get; set; }

    public string AvatarUrl { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public Guid? DeletedBy { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<Booking> BookingCustomers { get; set; } = new List<Booking>();

    public virtual ICollection<Booking> BookingDeletedByNavigations { get; set; } = new List<Booking>();

    public virtual ICollection<BookingStatusHistory> BookingStatusHistories { get; set; } = new List<BookingStatusHistory>();

    public virtual ICollection<Cancellation> Cancellations { get; set; } = new List<Cancellation>();

    public virtual ICollection<ChatHistory> ChatHistories { get; set; } = new List<ChatHistory>();

    public virtual ICollection<Conversation> ConversationGuests { get; set; } = new List<Conversation>();

    public virtual ICollection<Conversation> ConversationHosts { get; set; } = new List<Conversation>();

    public virtual User DeletedByNavigation { get; set; }

    public virtual ICollection<Homestay> HomestayDeletedByNavigations { get; set; } = new List<Homestay>();

    public virtual ICollection<Homestay> HomestayOwners { get; set; } = new List<Homestay>();

    public virtual ICollection<User> InverseDeletedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<Review> ReviewCustomers { get; set; } = new List<Review>();

    public virtual ICollection<Review> ReviewDeletedByNavigations { get; set; } = new List<Review>();

    public virtual ICollection<SupportTicket> SupportTicketStaffs { get; set; } = new List<SupportTicket>();

    public virtual ICollection<SupportTicket> SupportTicketUsers { get; set; } = new List<SupportTicket>();

    public virtual ICollection<TicketReply> TicketReplies { get; set; } = new List<TicketReply>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<VerificationDocument> VerificationDocumentReviewedByNavigations { get; set; } = new List<VerificationDocument>();

    public virtual ICollection<VerificationDocument> VerificationDocumentUsers { get; set; } = new List<VerificationDocument>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}