// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class VerificationDocument
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string DocumentType { get; set; }

    public string DocumentUrl { get; set; }

    public string Status { get; set; }

    public Guid? ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public string RejectReason { get; set; }

    public DateTime SubmissionDate { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual User ReviewedByNavigation { get; set; }

    public virtual User User { get; set; }
}