// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CHMS.DAL.Entities;

public partial class Wishlist
{
    public Guid UserId { get; set; }

    public Guid HomestayId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Homestay Homestay { get; set; }

    public virtual User User { get; set; }
}